name: Ruby Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        ruby:
          - 3.0

    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
        id: ruby

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run Test
        working-directory: ruby
        run: rake test
